visit = ['tokyo', 'rome', 'toronto', 'la', 'philadelphia']
print(visit)
print(sorted(visit))
print(visit)
visit.reverse()
print(visit)
visit.reverse()
print(visit)
visit.sort()
print(visit)
visit.sort(reverse=True)
print(visit)
